
platform :ios, '8.0'
use_frameworks!

target 'Cabbage_Example' do

    pod 'SnapKit', '~> 3.2.0'

    pod 'Cabbage', :path => '../'

    target 'Cabbage_Tests' do
        inherit! :search_paths
        
        
    end
end
