source 'https://github.com/CocoaPods/Specs.git'

platform :ios, '8.0'
use_frameworks!

target 'Cabbage_Example' do

    pod 'SnapKit', '~> 4.0.0'

    pod 'Cabbage', :path => '../'

    target 'Cabbage_Tests' do
        inherit! :search_paths
        
        
    end
end
